using TrackerOfTime.V2.M6.Memory;using TrackerOfTime.V2.M6.GameState;using TrackerOfTime.V2.M6.CheckState;using TrackerOfTime.V2.M6.RandomizerState;
namespace TrackerOfTime.V2.M6.SnapshotAdapter;
public sealed class GameSnapshotAdapter(GoldenRdramReader reader){
 public async Task<GameSnapshotAdapterResult> CaptureAsync(string provider,CheckScannerSettings checkSettings,CancellationToken ct=default){
  var game=await new OoTGameStateDecoder(reader).CaptureAsync(ct);var checks=await new OoTCheckStateDecoder(reader).CaptureAsync(game.LocationCode,checkSettings,ct);var rr=await new OoTR9136RuntimeDecoder(reader).CaptureAsync(ct);var f=await new GoldenFeatureDecoder(reader).CaptureAsync(ct);var map=GoldenReferenceMapCatalog.Decode(game.LocationCode,f.Room,game.Age);
  var mq=rr.Layout==OoTRLayoutStatus.OoTR9136FLum?MapMq(rr.DungeonIsMq):new MqSnapshot(false,false,Array.AsReadOnly(new bool[12]),"");var er=new EntranceRandomizerSnapshot(null,null,"M6.6 spoiler-safe: no ER routing inferred from CFG_DUNGEON_ENTRANCES; seed routing remains M3/OoTR authority");
  PlayerPositionSnapshot? pos=game.PlayerPosition is null?null:new(game.PlayerPosition.X,game.PlayerPosition.Y,game.PlayerPosition.Z,game.WastelandRotation);
  return new(DateTimeOffset.UtcNow,provider,new(game,SnapshotEvidence.Proven,"Frozen M6.3"),new((byte?)null,SnapshotEvidence.Unknown,"Golden GameSnapshot.CurrentRoom remains Unknown; room is Map-only"),new(map,map.MinimapAsset is null?SnapshotEvidence.Partial:SnapshotEvidence.Proven,"V1/M10 Golden map projection; room consumed only here"),new(f.Inventory,SnapshotEvidence.Proven,"M6.1 CONFIRMED V1 reads 0x11A644..0x11A673"),new(f.Equipment,SnapshotEvidence.Proven,"M6.1 CONFIRMED 0x11A66C + knife 0x11A60C"),new(f.Upgrades,SnapshotEvidence.Proven,"M6.1 CONFIRMED 0x11A670"),new(f.QuestItems,SnapshotEvidence.Proven,"M6.1 CONFIRMED 0x11A674"),new(f.Songs,SnapshotEvidence.Proven,"Golden quest bits 6..17"),new(f.DungeonItems,SnapshotEvidence.Proven,"M6.1 CONFIRMED 0x11A678/+4/+8 + Triforce 0x11AE94"),new(f.DungeonKeys,SnapshotEvidence.Proven,"Golden key packing 0x11A68C/690/694/698"),new(checks.Checks,SnapshotEvidence.Partial,"Frozen M6.4; Unknown/Unchecked/Checked preserved"),new(mq,rr.Layout==OoTRLayoutStatus.OoTR9136FLum?SnapshotEvidence.Proven:SnapshotEvidence.Unknown,"Frozen M6.5 14-byte MQ mapped to V1 12; Tower/Hideout N/A skipped"),new(er,SnapshotEvidence.Unknown,"No live ER route semantics proven in M6.5"),new(rr,rr.Layout==OoTRLayoutStatus.OoTR9136FLum?SnapshotEvidence.Proven:SnapshotEvidence.Unknown,"Frozen M6.5 exact-layout gated"),new(pos,pos is null?SnapshotEvidence.Unknown:SnapshotEvidence.Proven,"Frozen M6.3 player position"));}
 public static MqSnapshot MapMq(IReadOnlyList<bool>x){if(x.Count!=14)return new(false,false,Array.AsReadOnly(new bool[12]),string.Concat(x.Select(v=>v?'1':'0')));int[] i={0,1,2,3,4,5,6,7,8,9,11,13};return new(true,true,Array.AsReadOnly(i.Select(n=>x[n]).ToArray()),string.Concat(x.Select(v=>v?'1':'0')));}
}
