using System.Globalization;using TrackerOfTime.V2.M6.Memory;
namespace TrackerOfTime.V2.M6.SnapshotAdapter;
public sealed record GoldenFeatureSnapshot(InventorySnapshot Inventory,EquipmentSnapshot Equipment,UpgradesSnapshot Upgrades,QuestItemsSnapshot QuestItems,SongsSnapshot Songs,DungeonItemsSnapshot DungeonItems,DungeonKeySnapshot DungeonKeys,byte Room);
public sealed class GoldenFeatureDecoder(GoldenRdramReader r){
 static readonly string[] Names={"Deku Stick","Deku Nut","Bombs","Bow","Fire Arrow","Din's Fire","Fairy Slingshot","Fairy Ocarina","Ocarina of Time","Bombchus","Hookshot","Longshot","Ice Arrows","Farore's Wind","Boomerang","Lens of Truth","Magic Beans","Megaton Hammer","Light Arrows","Nayru's Love","Empty Bottle","Red Potion","Green Potion","Blue Potion","Bottled Fairy","Fish","Lon Lon Milk","Ruto's Letter","Blue Fire","Bug","Big Poe","Half Milk","Poe","Weird Egg","Chicken","Zelda's Letter","Keaton Mask","Skull Mask","Spooky Mask","Bunny Hood","Goron Mask","Zora Mask","Gerudo Mask","Mask of Truth","Sold Out","Pocket Egg","Pocket Cucco","Cojiro","Odd Mushroom","Odd Potion","Poacher's Saw","Broken Goron's Sword","Prescription","Eyeball Frog","Eye Drops","Claim Check"};
 static readonly (int,string)[] Eq={(16,"Kokiri Sword"),(17,"Master Sword"),(18,"Biggoron's Sword"),(19,"Broken Knife"),(20,"Deku Shield"),(21,"Hylian Shield"),(22,"Mirror Shield"),(24,"Kokiri Tunic"),(25,"Goron Tunic"),(26,"Zora Tunic"),(28,"Kokiri Boots"),(29,"Iron Boots"),(30,"Hover Boots")};
 static readonly (string,int,int)[] Up={("Quiver",0,1),("Bomb Bag",3,4),("Gauntlet",6,7),("Scale",9,10),("Wallet",12,13),("Bullet Bag",14,15),("Deku Stick Capacity",17,18),("Deku Nut Capacity",20,21)};
 static readonly string[] Quest={"Forest Medallion","Fire Medallion","Water Medallion","Spirit Medallion","Shadow Medallion","Light Medallion","Minuet of Forest","Bolero of Fire","Serenade of Water","Requiem of Spirit","Nocturne of Shadow","Prelude of Light","Zelda's Lullaby","Epona's Song","Saria's Song","Sun's Song","Song of Time","Song of Storms","Kokiri Emerald","Goron Ruby","Zora Sapphire","Stone of Agony","Gerudo's Membership Card"};
 public async Task<GoldenFeatureSnapshot> CaptureAsync(CancellationToken ct=default){
  var iw=new uint[6];var qw=new uint[6];for(int i=0;i<6;i++){iw[i]=await r.ReadUInt32Async(0x11A644+i*4,ct);qw[i]=await r.ReadUInt32Async(0x11A65C+i*4,ct);}var ib=Bytes(iw);var qb=Bytes(qw);var slots=new InventorySlotSnapshot[24];for(int i=0;i<24;i++){byte id=ib[i],q=qb[i];bool valid=id<=55,qty=id is 0 or 1 or 2 or 3 or 6 or 9;slots[i]=new(i,id,valid?Names[id]:"Empty Slot",q,valid&&(!qty||q!=0));}var inv=new InventorySnapshot(Array.AsReadOnly(slots),Array.AsReadOnly(iw),Array.AsReadOnly(qw));
  uint eq=await r.ReadUInt32Async(0x11A66C,ct),knife=await r.ReadUInt32Async(0x11A60C,ct);var ee=Eq.Select(x=>new EquipmentEntrySnapshot(x.Item1,x.Item2,Bit(eq,x.Item1))).ToArray();bool bgs=Bit(eq,18),broken=Bit(eq,19),kc=Bit(knife,8);string disp=bgs?"Biggoron's Sword":broken?"Broken Knife":"None";if(bgs&&!kc&&broken)disp="Broken Knife";var equipment=new EquipmentSnapshot(Array.AsReadOnly(ee),eq,knife,disp);
  uint up=await r.ReadUInt32Async(0x11A670,ct);var upgrades=new UpgradesSnapshot(Array.AsReadOnly(Up.Select(x=>new UpgradeStateSnapshot(x.Item1,(Bit(up,x.Item2)?1:0)+(Bit(up,x.Item3)?2:0))).ToArray()),up);
  uint qraw=await r.ReadUInt32Async(0x11A674,ct);var qe=Quest.Select((id,bit)=>new QuestItemSnapshot(bit,id,Bit(qraw,bit))).ToArray();var quest=new QuestItemsSnapshot(Array.AsReadOnly(qe),qraw);var songs=new SongsSnapshot(Array.AsReadOnly(qe.Where(x=>x.Bit is >=6 and <=17).Select(x=>new SongSnapshot(x.Bit,x.Id,x.Owned)).ToArray()));
  var dw=new uint[3];for(int i=0;i<3;i++)dw[i]=await r.ReadUInt32Async(0x11A678+i*4,ct);var db=Bytes(dw);var de=new DungeonItemEntrySnapshot[11];for(int i=0;i<11;i++){int v=db[i]&7;de[i]=new(i,i<=9?(v&4)!=0:null,i<=9?(v&2)!=0:null,i is >=3 and <=7 or 10?(v&1)!=0:null);}var di=new DungeonItemsSnapshot(Array.AsReadOnly(de),Array.AsReadOnly(dw),await r.ReadByteAsync(0x11AE94,ct));
  uint forest=await r.ReadByteAsync(0x11A68C,ct),temples=await r.ReadUInt32Async(0x11A690,ct),well=await r.ReadUInt32Async(0x11A694,ct),castle=await r.ReadUInt32Async(0x11A698,ct);string p=forest.ToString("X2",CultureInfo.InvariantCulture)+temples.ToString("X8",CultureInfo.InvariantCulture)+well.ToString("X8",CultureInfo.InvariantCulture)[..2]+well.ToString("X8",CultureInfo.InvariantCulture).Substring(6,2)+castle.ToString("X8",CultureInfo.InvariantCulture).Substring(2,2);var keys=Enumerable.Range(0,8).Select(i=>Convert.ToByte(p.Substring(i*2,2),16)).Select(v=>v==255?(byte)0:v>99?(byte)99:v).ToArray();
  return new(inv,equipment,upgrades,quest,songs,di,new(Array.AsReadOnly(keys),forest,temples,well,castle),await r.ReadByteAsync(0x1D8BEE,ct));}
 static byte[] Bytes(IEnumerable<uint>w){var a=new List<byte>();foreach(uint x in w){string h=x.ToString("X8",CultureInfo.InvariantCulture);for(int i=0;i<8;i+=2)a.Add(Convert.ToByte(h.Substring(i,2),16));}return a.ToArray();}static bool Bit(uint v,int b)=>(v&(1u<<b))!=0;
}
