<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><Platforms>AnyCPU;x64</Platforms></PropertyGroup><ItemGroup><ProjectReference Include="..\M6.Memory\TrackerOfTime.V2.M6.Memory.csproj" /><ProjectReference Include="..\M6.GameState\TrackerOfTime.V2.M6.GameState.csproj" /><ProjectReference Include="..\M6.CheckState\TrackerOfTime.V2.M6.CheckState.csproj" /><ProjectReference Include="..\M6.RandomizerState\TrackerOfTime.V2.M6.RandomizerState.csproj" /></ItemGroup></Project>
