<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><EnableWindowsTargeting>true</EnableWindowsTargeting><Platforms>AnyCPU;x64</Platforms></PropertyGroup><ItemGroup><ProjectReference Include="..\TrackerOfTime.V2.Randomizer\TrackerOfTime.V2.Randomizer.csproj" /></ItemGroup></Project>
